name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    outputs:
      packageVersionId: ${{ steps.release.outputs.packageVersionId }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm ci
          npm install --global @salesforce/cli
      - name: Authenticate DevHub and create scratch org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_DEVHUB }}" | sf org login sfdx-url --set-default-dev-hub --sfdx-url-stdin
          npm run develop
      - name: Run unit tests
        run: npm run test
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch -p
      - name: Release package
        id: release
        run: npx -y -p @semantic-release/exec -p @semantic-release/git -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
