name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          yarn install
          yarn global add @salesforce/cli
      - name: Authenticate DevHub and create scratch org
        run: |
          sf org login sfdx-url -a devhub -d -f <(echo "${{ secrets.SFDX_AUTH_URL_DEVHUB }}")
          yarn develop
      - name: Run unit tests
        run: yarn test
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch -p
      - name: Release package
        run: npx -p semantic-release-sfdx -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
